# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
target 'Xchangerator' do
  # Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/OAuth'

  pod 'GoogleSignIn'

# Optionally, include the Swift extensions if you're using Swift.
	pod 'FirebaseFirestoreSwift'
  # Pods for Xchangerator

end
